-- S-005: outr_twilio_calls table (18 columns)
CREATE TABLE IF NOT EXISTS outr_twilio_calls (
    id CHAR(36) NOT NULL,
    call_type ENUM('incoming', 'outgoing', 'missed', 'rejected') NOT NULL,
    agent_id CHAR(36) NULL,
    from_number VARCHAR(50) NULL,
    to_number VARCHAR(50) NULL,
    status VARCHAR(50) NULL,
    call_sid VARCHAR(255) NOT NULL,
    duration INT DEFAULT 0,
    recording_url TEXT NULL,
    recording_sid VARCHAR(255) NULL,
    parent_type VARCHAR(100) NULL,
    parent_id CHAR(36) NULL,
    company_id CHAR(36) NULL,
    notes TEXT NULL,
    cti_setting_id CHAR(36) NULL,
    date_created DATETIME NOT NULL,
    date_modified DATETIME NOT NULL,
    deleted TINYINT(1) DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_call_sid (call_sid),
    INDEX idx_call_type (call_type),
    INDEX idx_agent_id (agent_id),
    INDEX idx_parent (parent_type, parent_id),
    INDEX idx_company_id (company_id),
    INDEX idx_status (status),
    INDEX idx_date_created (date_created),
    INDEX idx_cti_setting (cti_setting_id),
    INDEX idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
