<?php
/**
 * SweetDialerCTI Language File (Epic 3)
 * CTI Settings Module
 */

$mod_strings['LBL_MODULE_NAME'] = 'Twilio CTI Settings';
$mod_strings['LBL_MODULE_TITLE'] = 'CTI Settings';
$mod_strings['LBL_ID'] = 'ID';
$mod_strings['LBL_NAME'] = 'Name';
$mod_strings['LBL_ACCOUNTS_SID'] = 'Account SID';
$mod_strings['LBL_AUTH_TOKEN'] = 'Auth Token';
$mod_strings['LBL_AGENT_PHONE_NUMBER'] = 'Agent Phone Number';
$mod_strings['LBL_PHONE_SID'] = 'Phone SID';
$mod_strings['LBL_INCOMING_CALLS_MODULES'] = 'Incoming Calls Module';
$mod_strings['LBL_STATUS'] = 'Status';
$mod_strings['LBL_BG_COLOR'] = 'Background Color';
$mod_strings['LBL_TEXT_COLOR'] = 'Text Color';
$mod_strings['LBL_API_KEY_SID'] = 'API Key SID';
$mod_strings['LBL_API_KEY_SECRET'] = 'API Key Secret';
$mod_strings['LBL_TWIML_APP_SID'] = 'TwiML App SID';
$mod_strings['LBL_DATE_CREATED'] = 'Date Created';
$mod_strings['LBL_DATE_MODIFIED'] = 'Date Modified';
$mod_strings['LBL_DELETED'] = 'Deleted';
$mod_strings['LBL_CREATED'] = 'Created By';
$mod_strings['LBL_MODIFIED_USER_ID'] = 'Modified By';
$mod_strings['LBL_NEW_FORM_TITLE'] = 'New CTI Setting';
$mod_strings['LBL_SEARCH_FORM_TITLE'] = 'Search CTI Settings';
$mod_strings['LNK_NEW_RECORD'] = 'Create CTI Setting';
$mod_strings['LNK_LIST'] = 'View CTI Settings';
$mod_strings['LBL_LIST_FORM_TITLE'] = 'CTI Settings List';
$mod_strings['LBL_LIST_NAME'] = 'Name';
$mod_strings['LBL_LIST_STATUS'] = 'Status';
$mod_strings['LBL_LIST_DATE_CREATED'] = 'Created';

// S-021: Relate Fields
$mod_strings['LBL_TWILIO_VOICE_MAIL'] = 'Twilio Voice Mail';
$mod_strings['LBL_TWILIO_VOICE_MAIL_ID'] = 'Voice Mail ID';
$mod_strings['LBL_OUTBOUND_INBOUND_AGENT'] = 'Outbound/Inbound Agent';
$mod_strings['LBL_OUTBOUND_INBOUND_AGENT_ID'] = 'Agent ID';

// S-023: File Upload Fields
$mod_strings['LBL_DUAL_RING_FILE'] = 'Dual Ring File';
$mod_strings['LBL_DUAL_RING_FILE_NAME'] = 'Dual Ring Filename';
$mod_strings['LBL_HOLD_RING_FILE'] = 'Hold Ring File';
$mod_strings['LBL_HOLD_RING_FILE_NAME'] = 'Hold Ring Filename';
$mod_strings['LBL_UPLOAD_MP3'] = 'Upload MP3 (max 10MB)';
$mod_strings['LBL_REMOVE_FILE'] = 'Remove';

// S-027: Validation Fields
$mod_strings['LBL_LAST_VALIDATION_STATUS'] = 'Last Validation Status';
$mod_strings['LBL_LAST_VALIDATION_MESSAGE'] = 'Last Validation Message';
$mod_strings['LBL_LAST_VALIDATION_DATE'] = 'Last Validated';
$mod_strings['LBL_VALIDATION_PASSED'] = 'PASSED ATTEMPT';
$mod_strings['LBL_VALIDATION_FAILED'] = 'Validation Failed';
$mod_strings['LBL_VALIDATION_NOT_RUN'] = 'Validation not yet run';

// S-031
$mod_strings['LBL_RING_TIMEOUT'] = 'Ring Timeout (seconds)';

// Custom View Messages
$mod_strings['LBL_NO_INCOMING_SETTINGS'] = 'No incoming call settings found.';
$mod_strings['LBL_NO_PHONE_NUMBERS_ASSIGNED'] = 'You do not have any phone numbers assigned.';
$mod_strings['LBL_NO_PARTNER_AGENTS'] = 'No partner agents found.';
$mod_strings['LBL_AGENT_NAME'] = 'Agent Name';
$mod_strings['LBL_SHARED_NUMBERS'] = 'Shared Numbers';
$mod_strings['LBL_CTI_SETTINGS'] = 'CTI Settings';
$mod_strings['LBL_SETTINGS'] = 'Settings';
$mod_strings['LBL_CONTACT'] = 'Contact';
$mod_strings['LBL_YOUR_PHONE_NUMBERS'] = 'Your Phone Numbers';
$mod_strings['LBL_TWIML_AUTO_GENERATED'] = 'Auto-generated by system';
